# Generated by Django 2.0.6 on 2018-09-09 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='telefono',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='imagen',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='genero',
        ),
        migrations.AddField(
            model_name='perfil',
            name='identificacion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
